Repository RevatureRobert/2106RNC-3-P2-BE, pull requests merged in 2021-07, with the labels that each got.

#12 Fixed serverless deployment and several dependency issues, many more …
  .gitignore
  deploy.ts
  package.json
  serverless.yml
  src/Server.ts
  src/index.ts
Labels: AWS actions, BackEnd, CodePipeLine, Lambda, bug

#13 Merging serverless deployment feature into dev.
  .gitignore
  deploy.ts
  package.json
  serverless.yml
  src/Server.ts
  src/index.ts
Labels: AWS actions, BackEnd, CodePipeLine, Lambda, Route53, bug

#15 removed @ symbol
  src/@types/express/index.d.ts
  src/daos/Messages/MessagesDao.test.ts
  src/daos/Messages/MessagesDao.ts
  src/daos/SocialPost/SocialPostDao.test.ts
  src/daos/User/UserDao.test.ts
Labels: BackEnd, bug

#16 Fixed a few broken imports.
  src/entities/User.ts
  src/index.ts
Labels: BackEnd, bug

#17 Update from project one
  package.json
  src/@types/express/index.d.ts
  src/Server.ts
  src/daos/FaB/FaB.test.ts
  src/daos/FaB/FaB.ts
  src/daos/Messages/MessagesDao.test.ts
  src/daos/Messages/MessagesDao.ts
  src/daos/MockDb/MockDao.mock.ts
  src/daos/MockDb/MockDb.backup.json
  src/daos/MockDb/MockDb.json
  src/daos/Notifications/Notifications.test.ts
  src/daos/Notifications/Notifications.ts
  src/daos/README.md
  src/daos/Shared/dynamodb_batch_delete.ts
  src/daos/SocialPost/SocialPostDao.test.ts
  src/daos/SocialPost/SocialPostDao.ts
  src/daos/User/UserDao.test.ts
  src/daos/User/UserDao.ts
  src/entities/FaB.ts
  src/entities/Messages.ts
  src/entities/Notification.ts
  src/entities/SocialPosts.ts
  src/entities/User.ts
  src/index.test.ts
  src/index.ts
  src/pre-start/env/development.env
  src/pre-start/env/production.env
  src/pre-start/env/test.env
  src/pre-start/index.ts
  src/pre-start/testObjects.ts
  src/pre-start/testenviroment.ts
  src/public/scripts/index.js
  src/public/stylesheets/style.css
  src/routes/FaBs.ts
  src/routes/Messages.ts
  src/routes/Notifcations.ts
  src/routes/SocialPosts.ts
  src/routes/Users.ts
  src/routes/index.ts
  src/shared/Logger.ts
  src/shared/Security.ts
  src/shared/constants.ts
  src/shared/functions.ts
Labels: AWS actions, BackEnd, CodePipeLine, Lambda, Route53, Testing, bug, documentation, enhancement

#18 Fixed DAOs to depend on lambda role permissions for database access...
  src/daos/Messages/MessagesDao.ts
  src/daos/Shared/dynamodb_batch_delete.ts
  src/daos/SocialPost/SocialPostDao.ts
  src/daos/User/UserDao.ts
Labels: AWS actions, BackEnd, Lambda, bug

#29 Matthew
  src/daos/SocialPost/SocialPostDao.ts
Labels: BackEnd

#30 Update SocialPostDao.ts
  .Dockerignore
  .gitignore
  .husky/pre-commit
  .prettierignore
  .vscode/settings.json
  Dockerfile
  buildspec.yml
  deploy.ts
  docker-compose.yml
  package.json
  serverless.yml
  src/@types/express/index.d.ts
  src/Server.ts
  src/daos/FaB/FaB.test.ts
  src/daos/FaB/FaB.ts
  src/daos/Messages/MessagesDao.test.ts
  src/daos/Messages/MessagesDao.ts
  src/daos/MockDb/MockDao.mock.ts
  src/daos/MockDb/MockDb.backup.json
  src/daos/MockDb/MockDb.json
  src/daos/Notifications/Notifications.test.ts
  src/daos/Notifications/Notifications.ts
  src/daos/README.md
  src/daos/Shared/dynamodb_batch_delete.ts
  src/daos/SocialPost/SocialPostDao.test.ts
  src/daos/SocialPost/SocialPostDao.ts
  src/daos/User/UserDao.test.ts
  src/daos/User/UserDao.ts
  src/entities/FaB.ts
  src/entities/Messages.ts
  src/entities/Notification.ts
  src/entities/SocialPosts.ts
  src/entities/User.ts
  src/index.test.ts
  src/index.ts
  src/pre-start/env/development.env
  src/pre-start/env/production.env
  src/pre-start/env/test.env
  src/pre-start/index.ts
  src/pre-start/testObjects.ts
  src/pre-start/testenviroment.ts
  src/public/scripts/index.js
  src/public/stylesheets/style.css
  src/routes/FaBs.ts
  src/routes/Messages.ts
  src/routes/Notifcations.ts
  src/routes/SocialPosts.ts
  src/routes/Users.ts
  src/routes/index.ts
  src/shared/Logger.ts
  src/shared/Security.ts
  src/shared/constants.ts
  src/shared/functions.ts
Labels: BackEnd, CodePipeLine, Lambda

#31 Matthew
  README.md
  buildspec.yml
  src/daos/SocialPost/SocialPostDao.ts
Labels: AWS actions, BackEnd, CodePipeLine, Lambda

#37 updates
  README.md
  package.json
  src/index.ts
Labels: CodePipeLine, bug, documentation

#40 Matthew
  README.md
  src/daos/Messages/MessagesDao.test.ts
  src/daos/SocialPost/SocialPostDao.test.ts
  src/daos/User/UserDao.test.ts
  src/index.test.ts
Labels: AWS actions, BackEnd, CodePipeLine, bug

#41 Matthew
  README.md
  src/daos/Messages/MessagesDao.test.ts
  src/daos/SocialPost/SocialPostDao.test.ts
  src/daos/User/UserDao.test.ts
Labels: AWS actions, BackEnd, CodePipeLine, bug, documentation

#42 updates to DAO and buildspec
  buildspec-test.yml
  src/daos/Messages/MessagesDao.test.ts
  src/daos/SocialPost/SocialPostDao.test.ts
  src/daos/User/UserDao.test.ts
Labels: AWS actions, BackEnd, CodePipeLine, bug, documentation

#43 Dev branch
  buildspec-test.yml
  src/daos/Messages/MessagesDao.test.ts
  src/daos/SocialPost/SocialPostDao.test.ts
  src/daos/User/UserDao.test.ts
Labels: AWS actions, BackEnd, CodePipeLine, bug, documentation

#44 copepipeline test 1
  buildspec-test.yml
  src/daos/Messages/MessagesDao.test.ts
  src/daos/SocialPost/SocialPostDao.test.ts
  src/daos/User/UserDao.test.ts
Labels: AWS actions, BackEnd, CodePipeLine, bug, documentation

#45 Dev branch
  buildspec-test.yml
  src/daos/Messages/MessagesDao.test.ts
  src/daos/SocialPost/SocialPostDao.test.ts
  src/daos/User/UserDao.test.ts
Labels: AWS actions, BackEnd, CodePipeLine, bug, documentation

#47 Matthew
  src/daos/SocialPost/SocialPostDao.ts
Labels: BackEnd, bug

#48 Dev branch
  src/daos/SocialPost/SocialPostDao.ts
Labels: BackEnd, bug
